import { z } from "zod/v4";

// Enums — match existing types/trip.ts
export const TripStatusSchema = z.enum(["draft", "planned", "active", "completed"]);
export type TripStatus = z.infer<typeof TripStatusSchema>;

export const ExperienceCategorySchema = z.enum([
  "trekking",
  "city",
  "lago",
  "castle",
  "nature",
  "adventure",
  "rest",
  "waterfall",
  "drive",
  "drone",
]);
export type ExperienceCategory = z.infer<typeof ExperienceCategorySchema>;

export const ExperienceLinkTypeSchema = z.enum([
  "tripadvisor",
  "alltrails",
  "getyourguide",
  "booking",
  "website",
  "official",
]);

// Models — field names match existing types/trip.ts (camelCase, not Python snake_case)
export const ExperienceLinkSchema = z.object({
  type: ExperienceLinkTypeSchema,
  url: z.string(),
});

export const ExperienceSchema = z.object({
  name: z.string(),
  desc: z.string(),
  category: ExperienceCategorySchema,
  time: z.string(),
  cost: z.string(),
  links: z.array(ExperienceLinkSchema).optional(),
});

export const ScheduleItemSchema = z.object({
  t: z.string(),
  a: z.string(),
});

export const RestaurantSchema = z.object({
  name: z.string(),
  meal: z.string(),
  desc: z.string(),
  url: z.string().optional(),
});

export const TripDaySchema = z.object({
  num: z.string(),
  // date + isoDate are LEGACY fields kept optional during the derived-trip-
  // dates transition. New JSONs (from skill `/travel-planner` export) MUST NOT
  // emit them — they're computed from trip.startDate + index via
  // dayIsoDate / dayDateBR (src/lib/utils/trip-dates.ts). Existing JSONs
  // (italy-2026, scotland_*, vegas_*) still ship them; the publish endpoint
  // stores `data` jsonb verbatim, so the legacy fields hang around until the
  // strip-derived-dates one-shot script runs (Phase 6 of the refactor).
  // Treat as ground-truth-equivalent ONLY when comparing against derived
  // values; never trust them as the source of truth.
  date: z.string().optional(),
  title: z.string(),
  tags: z.array(z.string()),
  cls: z.string(),
  isoDate: z.string().optional(),
  desc: z.string().optional(),
  schedule: z.array(ScheduleItemSchema).optional(),
  experiences: z.array(ExperienceSchema).optional(),
  restaurant: RestaurantSchema.optional(),
  warnings: z.array(z.string()).optional(),
  dayCost: z.string().optional(),
  camp: z.string().optional(),
  driving: z.string().optional(),
  planB: z.string().optional(),
});

export const ChecklistItemSchema = z.object({
  id: z.string(),
  text: z.string(),
  done: z.boolean().optional(),
  critical: z.boolean().optional(),
});

export const ChecklistGroupSchema = z.object({
  title: z.string(),
  items: z.array(ChecklistItemSchema),
});

export const PackingItemSchema = z.object({
  id: z.string(),
  text: z.string(),
});

export const PackingGroupSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  items: z.array(PackingItemSchema),
});

export const BookingSchema = z.object({
  date: z.string(),
  isoDate: z.string().optional(),
  status: z.enum(["confirmed", "critical", "pending"]),
  document: z.string(),
  company: z.string(),
  link: z.string().optional(),
  linkLabel: z.string().optional(),
});

// Budget item id is a stable slug (kebab-case, alphanumeric). Generated by the
// advisor in the .md and propagated through the export → publish pipeline.
// Expenses reference items by this id (soft link — budget lives in jsonb).
// Special slug `unplanned` is reserved for the buffer/imprevistos item that
// every trip must have.
export const BudgetItemSchema = z.object({
  id: z.string().regex(/^[a-z0-9][a-z0-9-]*$/, {
    message: "id must be lowercase kebab-case (e.g. 'flights', 'tolls-vinhetas', 'unplanned')",
  }),
  category: z.string(),
  amount: z.number(),
  pct: z.number(),
  status: z.enum(["paid", "confirmed", "estimated", "reserve"]),
  notes: z.string(),
});

// Map data — see docs/spec/map.md.
// Two views (trip overview + day detail) feed off ONE schema. POI/route
// visibility is governed by `dayNum`: omitted = trip-wide, set = day-specific.
//
// IDs are stable strings used by the (future) chat tool to target mutations.
// Generated by the advisor pipeline as `kebab(name) + counter`; by the chat
// tool as nanoid. Uniqueness enforced inside the JSON via `.refine()` — no
// SQL constraint needed.

export const MapPOICategorySchema = z.enum(["attraction", "stay", "food", "shopping", "transport"]);

// Closed enum — adding a kind requires a code change (icon + colour mapping
// lives in InteractiveMap.tsx's categoryStyle table). Kind is unique across
// categories so the parser can map a single-token KML <styleUrl> back to
// (category, kind) without ambiguity.
export const MapPOIKindSchema = z.enum([
  // attraction
  "nature",
  "lake",
  "castle",
  "trek",
  "scenic",
  "viewpoint",
  "waterfall",
  "cave",
  "city",
  "vila",
  "unesco",
  "memorial",
  "wellness",
  "adventure",
  // stay
  "hotel",
  "camp",
  "apartment",
  // food
  "restaurant",
  "coffee",
  "bar",
  // shopping
  "shop",
  "market",
  // transport
  "headline",
  "destination",
  "ferry",
  "parking",
  "station",
]);

export const MapSourceSchema = z.enum(["advisor", "chat", "ui"]);

export const MapPOISchema = z.object({
  /** Stable id — chat tool targets via this. Unique within the trip. */
  id: z.string(),
  name: z.string(),
  description: z.string(),
  category: MapPOICategorySchema,
  kind: MapPOIKindSchema,
  lat: z.number(),
  lng: z.number(),
  /** Omit = trip-wide (visible in overview). Set = day-specific. */
  dayNum: z.number().int().positive().optional(),
  /** Ordering within a day's visit itinerary. */
  position: z.number().int().optional(),
  source: MapSourceSchema.default("advisor"),
});

export const MapRouteKindSchema = z.enum(["driving", "walking", "ferry", "transit"]);

export const MapRouteSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: z.string(),
  kind: MapRouteKindSchema,
  /** Omit = trip-wide overview polyline. Set = drawn only inside day N. */
  dayNum: z.number().int().positive().optional(),
  coordinates: z.array(z.object({ lat: z.number(), lng: z.number() })),
  source: MapSourceSchema.default("advisor"),
});

export const TripMapDataSchema = z
  .object({
    pois: z.array(MapPOISchema),
    routes: z.array(MapRouteSchema),
  })
  .refine((m) => new Set(m.pois.map((p) => p.id)).size === m.pois.length, {
    message: "POI ids must be unique within trip",
  })
  .refine((m) => new Set(m.routes.map((r) => r.id)).size === m.routes.length, {
    message: "Route ids must be unique within trip",
  });

export const TripSchema = z.object({
  id: z.string().optional(),
  slug: z.string(),
  title: z.string(),
  destination: z.string(),
  startDate: z.string(),
  // LEGACY input field. Optional during transition — new exports omit it,
  // legacy JSONs still carry it. Server-side, endDate is derived from
  // startDate + days.length - 1 at read time (rowToTrip / rowToSummary).
  // The TS Trip type re-asserts endDate as required string post-hydration
  // so consumers can keep reading `trip.endDate` until Phase 4 refactors
  // them to use `tripEndDate(trip)` directly.
  endDate: z.string().optional(),
  status: TripStatusSchema,
  currency: z.string(),
  coverImage: z.string().optional(),
  isPublic: z.boolean().optional(),
  mapEmbedUrl: z.string().optional(),
  ogImage: z.string().optional(),
  /** IANA timezone for the destination (e.g. "Europe/Rome"). Drives todayISO() */
  timezone: z.string().optional(),
  days: z.array(TripDaySchema),
  checklist: z.array(ChecklistGroupSchema).optional(),
  packing: z.array(PackingGroupSchema).optional(),
  bookings: z.array(BookingSchema).optional(),
  budget: z.array(BudgetItemSchema).optional(),
});

export const TripSummarySchema = z.object({
  slug: z.string(),
  title: z.string(),
  destination: z.string(),
  startDate: z.string(),
  endDate: z.string(),
  status: TripStatusSchema,
  coverImage: z.string().optional(),
  dayCount: z.number(),
  isPublic: z.boolean(),
});

// API input schemas (for creating/updating trips via API routes)
export const TripCreateSchema = z.object({
  title: z.string(),
  destination: z.string(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  currency: z.string().default("EUR"),
});
export type TripCreate = z.infer<typeof TripCreateSchema>;

export const TripUpdateSchema = z.object({
  title: z.string().optional(),
  destination: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  status: TripStatusSchema.optional(),
  currency: z.string().optional(),
});
export type TripUpdate = z.infer<typeof TripUpdateSchema>;
